version: '3.8'

services:
  project-test-a-nginx:
    image: nginx:alpine
    container_name: 'project-test-a-nginx'
    volumes:
      - ./nginx:/etc/nginx/conf.d
    environment:
      VIRTUAL_HOST: qr-bistor-notification-api-2.tent-official.com
    restart: always
  # app เปลี่ยนชื่อตามชื่อ service ถ้ามีหลายอันก็อย่าซ้ำกัน
  project-test-a:
    image: project-test-a:latest
    build: .
    container_name: "project-test-a"
    env_file:
      - ./.env
    restart: always

networks:
  default:
    name: docker-network
    external: true