version: '3.8'

services:
  qr-bistor-notification-api-2-nginx:
    image: nginx:alpine
    container_name: 'qr-bistor-notification-api-nginx'
    volumes:
      - ./nginx:/etc/nginx/conf.d
    environment:
      VIRTUAL_HOST: qr-bistor-notification-api-2.tent-official.com
    restart: always
  # app เปลี่ยนชื่อตามชื่อ service ถ้ามีหลายอันก็อย่าซ้ำกัน
  qr-bistor-notification-api-2:
    image: qr-bistor-notification-api:latest
    build: .
    container_name: "qr-bistor-notification-api-2"
    env_file:
      - ./.env
    restart: always

networks:
  default:
    name: docker-network
    external: true