version: '3.8'

services:
  project-a-api-nginx:
    image: nginx:alpine
    container_name: 'project-a-api-nginx'
    volumes:
      - ./nginx:/etc/nginx/conf.d
    environment:
      VIRTUAL_HOST: project-a-tent-api.tent-official.com
    restart: always
  # app เปลี่ยนชื่อตามชื่อ service ถ้ามีหลายอันก็อย่าซ้ำกัน
  project-a-api:
    image: project-a-api:latest
    build: .
    container_name: "project-a-api"
    env_file:
      - ./.env
    restart: always

networks:
  default:
    name: docker-network
    external: true
